spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviewatchlist
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

omdb:
  api:
    key: YOUR_KEY_HERE
    base-url: https://www.omdbapi.com
