spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviewatchlist
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

omdb:
  api:
    key: YOUR_OMDB_KEY
    base-url: https://www.omdbapi.com

jwt:
  secret: YOUR_JWT_SECRET
  expiration: 86400000